### ISSUE TITLE
Another dropdown in Customer

### ISSUE THREAD

**Issue by iamB0rgy** [MGeurts/laravel-9-bootstrap-5-datatables#1]
Hi, 

I have added another dropdown in Customer. I am able to Add New Customer but when I tried to edit a customer, the second dropdown doesn't populate the selected option. It is just showing as empty dropdown. Here's my code.

My View:

`
                            <div class="col-md-8">
                                <select name="payment_terms" id="payment_terms" class="form-select">
                                    <option value="">Choose ...</option>
                                    @foreach ($paymentTerms as $paymentTerm)
                                        @if ($paymentTerm->id == $customer->payment_terms)
                                            <option value="{{ $paymentTerm->id }}" selected>{{ $paymentTerm->payment_term }}
                                            </option>
                                        @else
                                            <option value="{{ $paymentTerm->id }}">{{ $paymentTerm->payment_term }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @error('payment_terms')
                                    <span class="invalid-feedback" role="alert">{{ $message }}</span>
                                @enderror
                            </div>`

My Controller:

`    public function edit(Customer $customer)
    {
        $countries = Country::where('is_eu', 1)->orderBy('name', 'asc')->get();
        $paymentTerms = PaymentTerms::all(); 

        return view('backend.customers.edit', compact('customer'))->with(['countries' => $countries, 'paymentTerms' => $paymentTerms]);
    }`

**Comment by MGeurts** [comment]
In your controller, add the following line to check if $paymentTerms containes any data:

dd(paymentTerms );

If it does, remove the dd() line and alter the return line like this:

return view('back.customers.edit', compact('customer'))->with(compact(['countries', 'paymentTerms']));

**Comment by iamB0rgy** [comment]
Yes, this `dd($paymentTerms);` returns my data. 

But this `return view('back.customers.edit', compact('customer'))->with(compact(['countries', 'paymentTerms']));` doesn't work. 

It is returning an empty dropdown.

**Comment by iamB0rgy** [comment]
It worked bro! Thanks!

**Comment by MGeurts** [comment]
Perfect.
