### ISSUE TITLE
Responsive Dt

### ISSUE THREAD

**Issue by iamB0rgy** [MGeurts/laravel-9-bootstrap-5-datatables#2]
Hi,

Is it possible to make the datatables responsive? I have added the below in `backend.components.datatables-js` but no luck.

`responsive: true,`

Thanks.

**Comment by MGeurts** [comment]
You also have to add the JS reference to backend.components.datatables-js :

<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
